### ISSUE TITLE
Blender 4.2 Errors when trying to create first colormap

### ISSUE THREAD

**Issue by LawrenceTattrie** [TheJeran/Blender-Colormaps#8]
This add-on seems to be exactly what I want but . . .
Has the blender interface changed for 4.2?
[blender_console.txt](https://github.com/user-attachments/files/16838960/blender_console.txt)

Attached is a copy of the console log showing python errors:

all_cmaps = sorted(matplotlib.colormaps(), key = lambda x: x.lower())
NameError: name 'matplotlib' is not defined. Did you mean: 'matplot'?

cmap = matplotlib.cm.get_cmap(cmap_name)
NameError: name 'matplotlib' is not defined

 cmap = LinearSegmentedColormap.from_list(cmap_name,list(col_list))
NameError: name 'LinearSegmentedColormap' is not defined

**Comment by TheJeran** [comment]
The libraries aren't installed. Go check the Colormaps addon in your preferences.

![image](https://github.com/user-attachments/assets/65dd4a77-b739-438c-9b4e-c43d452f07cb)

There will be a button there to install the libraries

**Comment by LawrenceTattrie** [comment]
There is no button to Install Dependencies.
![Blender 4 2 Screenshot](https://github.com/user-attachments/assets/596397af-12a6-4f07-9bdb-3ee22039a3c5)

**Comment by SchmidL** [comment]
Same for me - using Blender 4.2.1 LTS on a Windows 11 system

**Comment by TheJeran** [comment]
@LawrenceTattrie @SchmidL 

Sorry for long reply. Was on Holidays and forgot about this.

So the error you are getting is because matplotlib is not installed in blenders python environment. I'm unsure why my little Dependency missing code isn't detecting that correctly. I'll have a look.

In the meantime you both can solve this manually.

open your command window with `windows + R` and type `cmd` and hit enter

navigate to where your Blender Install/Folder is. If you use blender installer then the default is

`C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\bin`

When you reach that bin folder. Copy the directory and then paste that in the command window after "cd"

`cd C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\bin`

now type 

`python.exe -m pip install matplotlib cmocean`

This will install the two libraries you will need into blenders python environment

**Comment by LawrenceTattrie** [comment]
I have tried what you have asked but now I am getting errors listed in the console window saying the python version does not match the numpy version. I have uninstalled Blender and deleted the C:\users\x\appdata\roming\Blender Foundation\Blender\4.2. Then installed a new Blender 4.2 and the numpy version error continues. I have opened a ticket on Blender.org (#127813) because I do not understand how to set up blender without this conflict.

**Comment by SchmidL** [comment]
@LawrenceTattrie Thank you very much, and nothing to excuse!

I tried, but i think that with the windows user permission, we cannot write toe the site-packages of blender. And as I'm on a managed workstation, I will also not be able to change that.

That was the console response
`Defaulting to user installation because normal site-packages is not writeable`

Nevermind, I will wait for the update, or the bugfix from blender :)

**Comment by LawrenceTattrie** [comment]
Sorry for causing you extra work but I am going to stop trying to get this to code to work and try to get my regular blender back to working. The Blender people have closed my bug report saying it is not Blender's problem.

**Comment by SchmidL** [comment]
I found a way to do it: 

`"C:\Program Files\Blender Foundation\Blender 4.3\4.3\python\bin\python.exe" -m pip install --target="C:\Program Files\Blender Foundation\Blender 4.3\4.3\python\lib\site-packages" matplotlib cmocean`

**Comment by TheJeran** [comment]
> I found a way to do it:
> 
> `"C:\Program Files\Blender Foundation\Blender 4.3\4.3\python\bin\python.exe" -m pip install --target="C:\Program Files\Blender Foundation\Blender 4.3\4.3\python\lib\site-packages" matplotlib cmocean`

Great! I'll add that to the Readme. Thanks

**Comment by smlpt** [comment]
@TheJeran 
I tried the above mentioned workaround on my work machine with Blender 4.3 and 4.4 and in both cases the matplotlib library seems to be installed correctly in the site-packages folder (and the addon also detects it in the settings section).
But opening Blender as user and trying to import a colormap results in errors that originate from the matplotlib library not being found. I tested this by creating a new script in Blender and simply tried and failed to "import matplotlib as foo". Could this be a permission issue again? Admin installs the package, and so the normal user won't have access to it?
